# appspec.yml

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/gongsamo/build/

permissions:
  - object: /
    pattern : "**"
    mode : 755
    owner : ubuntu
    group : ubuntu

hooks:
  ApplicationStart:
    - location: /home/ubuntu/gongsamo/build/deploy.sh
      timeout: 600
      runas: ubuntu
  ValidateService:
    - location: /home/ubuntu/gongsamo/build/healthCheck.sh
      timeout: 60
      runas: ubuntu

